name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Storage
        run: df -h
      - name: CPU
        run: sudo cat /proc/cpuinfo
      - name: RAM
        run: sudo lshw -c memory
      - name: ALL
        run: sudo lshw
      - name: bench storage
        run: |
          sudo lsblk
          sudo hdparm -Ttv /dev/sda1
          sudo hdparm -Ttv /dev/sdb1
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Summary
        run: system_profiler SPHardwareDataType
      - name: Storage Space
        run: df -H
      - name: CPU
        run: sysctl -a | grep machdep.cpu
      - name: RAM
        run: system_profiler SPHardwareDataType | grep "  Memory:"
      - name: ALL
        run: system_profiler
      - name: bench storage
        run: |
          diskutil list
          sudo hdparm -Ttv /dev/sda1
          sudo hdparm -Ttv /dev/sdb1

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Summary
        run: systeminfo
      - name: Storage
        run: fsutil fsinfo drives
      - name: CPU
        run: wmic cpu get NumberOfCores
      - name: RAM
        run: wmic MEMORYCHIP get banklabel, capacity, caption, devicelocator, partnumber
      - name: ALL
        run: Get-ComputerInfo
      - name: Storage Details
        run: wmic diskdrive get Name,Model,SerialNumber,Size,Status
