name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}
          path: ${{github.workspace}}/vcpkg-binary-cache

      - name: Install dependencies
        env:
          VCPKG_BINARY_SOURCES: clear;files,${{github.workspace}}/vcpkg-binary-cache,readwrite
        run: |
          vcpkg install --debug spdlog abseil

      - name: Cleanup vcpkg cache
        shell: bash
        run: |
          python3 ./cleanup_vcpkg_cache.py "${VCPKG_INSTALLATION_ROOT}/installed" "${{github.workspace}}/vcpkg-binary-cache"

